name: gizi-balita-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - mlflow
      - dagshub
      - pandas
      - scikit-learn
      - matplotlib
      - seaborn
      - joblib
